services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: flowly
      POSTGRES_PASSWORD: flowlypass
      POSTGRES_DB: flowly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: