export const EXERCISE_MUSCLE_GROUPS = [
  'CHEST',
  'BACK',
  'LEGS',
  'SHOULDERS',
  'BICEPS',
  'TRICEPS',
  'ABS',
  'GLUTES',
  'CARDIO',
  'FULL_BODY',
  'OTHER',
] as const

export type ExerciseMuscleGroupValue = (typeof EXERCISE_MUSCLE_GROUPS)[number]

export interface SystemExerciseSeed {
  namePt: string
  nameEn: string
  muscleGroup: ExerciseMuscleGroupValue
  equipment?: string
  imageUrl?: string
}

export const SYSTEM_EXERCISES: SystemExerciseSeed[] = [
  // CHEST - 15 exercises
  { namePt: 'Supino reto', nameEn: 'Bench Press', muscleGroup: 'CHEST', equipment: 'Barbell' },
  { namePt: 'Supino inclinado', nameEn: 'Incline Bench Press', muscleGroup: 'CHEST', equipment: 'Barbell' },
  { namePt: 'Supino declinado', nameEn: 'Decline Bench Press', muscleGroup: 'CHEST', equipment: 'Barbell' },
  { namePt: 'Supino com halteres', nameEn: 'Dumbbell Bench Press', muscleGroup: 'CHEST', equipment: 'Dumbbell' },
  { namePt: 'Supino inclinado com halteres', nameEn: 'Incline Dumbbell Press', muscleGroup: 'CHEST', equipment: 'Dumbbell' },
  { namePt: 'Crucifixo com halteres', nameEn: 'Dumbbell Fly', muscleGroup: 'CHEST', equipment: 'Dumbbell' },
  { namePt: 'Crucifixo inclinado', nameEn: 'Incline Dumbbell Fly', muscleGroup: 'CHEST', equipment: 'Dumbbell' },
  { namePt: 'Cross over', nameEn: 'Cable Fly', muscleGroup: 'CHEST', equipment: 'Cable' },
  { namePt: 'Flexao de bracos', nameEn: 'Push-up', muscleGroup: 'CHEST', equipment: 'Bodyweight' },
  { namePt: 'Flexao com halteres', nameEn: 'Dumbbell Floor Press', muscleGroup: 'CHEST', equipment: 'Dumbbell' },
  { namePt: 'Supino em maquina', nameEn: 'Machine Chest Press', muscleGroup: 'CHEST', equipment: 'Machine' },
  { namePt: 'Peck deck', nameEn: 'Pec Deck', muscleGroup: 'CHEST', equipment: 'Machine' },
  { namePt: 'Crucifixo no cabo baixo', nameEn: 'Low Cable Fly', muscleGroup: 'CHEST', equipment: 'Cable' },
  { namePt: 'Mergulho', nameEn: 'Dip', muscleGroup: 'CHEST', equipment: 'Bodyweight' },
  { namePt: 'Supino Smith', nameEn: 'Smith Machine Bench Press', muscleGroup: 'CHEST', equipment: 'Machine' },

  // BACK - 18 exercises
  { namePt: 'Remada curvada', nameEn: 'Bent-over Row', muscleGroup: 'BACK', equipment: 'Barbell' },
  { namePt: 'Remada unilateral', nameEn: 'One-arm Dumbbell Row', muscleGroup: 'BACK', equipment: 'Dumbbell' },
  { namePt: 'Remada com halteres', nameEn: 'Dumbbell Row', muscleGroup: 'BACK', equipment: 'Dumbbell' },
  { namePt: 'Puxada alta', nameEn: 'Lat Pulldown', muscleGroup: 'BACK', equipment: 'Cable' },
  { namePt: 'Puxada alta aberta', nameEn: 'Wide Grip Lat Pulldown', muscleGroup: 'BACK', equipment: 'Cable' },
  { namePt: 'Puxada com triangulo', nameEn: 'V-bar Pulldown', muscleGroup: 'BACK', equipment: 'Cable' },
  { namePt: 'Barra fixa', nameEn: 'Pull-up', muscleGroup: 'BACK', equipment: 'Bodyweight' },
  { namePt: 'Barra fixa aberta', nameEn: 'Wide Grip Pull-up', muscleGroup: 'BACK', equipment: 'Bodyweight' },
  { namePt: 'Barra fixa assistida', nameEn: 'Assisted Pull-up', muscleGroup: 'BACK', equipment: 'Machine' },
  { namePt: 'Levantamento terra', nameEn: 'Deadlift', muscleGroup: 'BACK', equipment: 'Barbell' },
  { namePt: 'Remada baixa', nameEn: 'Seated Cable Row', muscleGroup: 'BACK', equipment: 'Cable' },
  { namePt: 'Remada maquina', nameEn: 'Machine Row', muscleGroup: 'BACK', equipment: 'Machine' },
  { namePt: 'Remada T', nameEn: 'T-bar Row', muscleGroup: 'BACK', equipment: 'Barbell' },
  { namePt: 'Remada com peso corporal', nameEn: 'Inverted Row', muscleGroup: 'BACK', equipment: 'Bodyweight' },
  { namePt: 'Puxada alta por tras', nameEn: 'Behind Neck Pulldown', muscleGroup: 'BACK', equipment: 'Cable' },
  { namePt: 'Voador costas', nameEn: 'Rear Machine Fly', muscleGroup: 'BACK', equipment: 'Machine' },
  { namePt: 'Levantamento terra romeno', nameEn: 'Romanian Deadlift', muscleGroup: 'BACK', equipment: 'Barbell' },
  { namePt: 'Remada pendlay', nameEn: 'Pendlay Row', muscleGroup: 'BACK', equipment: 'Barbell' },

  // LEGS - 22 exercises
  { namePt: 'Agachamento livre', nameEn: 'Back Squat', muscleGroup: 'LEGS', equipment: 'Barbell' },
  { namePt: 'Agachamento frontal', nameEn: 'Front Squat', muscleGroup: 'LEGS', equipment: 'Barbell' },
  { namePt: 'Agachamento goblet', nameEn: 'Goblet Squat', muscleGroup: 'LEGS', equipment: 'Dumbbell' },
  { namePt: 'Agachamento com halteres', nameEn: 'Dumbbell Squat', muscleGroup: 'LEGS', equipment: 'Dumbbell' },
  { namePt: 'Agachamento Sissy', nameEn: 'Sissy Squat', muscleGroup: 'LEGS', equipment: 'Bodyweight' },
  { namePt: 'Agachamento piscina', nameEn: 'Wall Sit', muscleGroup: 'LEGS', equipment: 'Bodyweight' },
  { namePt: 'Leg press', nameEn: 'Leg Press', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Leg press 45', nameEn: '45-Degree Leg Press', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Cadeira extensora', nameEn: 'Leg Extension', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Mesa flexora', nameEn: 'Leg Curl', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Mesa flexora deitado', nameEn: 'Lying Leg Curl', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Afundo', nameEn: 'Lunge', muscleGroup: 'LEGS', equipment: 'Bodyweight' },
  { namePt: 'Afundo com halteres', nameEn: 'Dumbbell Lunge', muscleGroup: 'LEGS', equipment: 'Dumbbell' },
  { namePt: 'Afundo inverso', nameEn: 'Reverse Lunge', muscleGroup: 'LEGS', equipment: 'Bodyweight' },
  { namePt: 'Step up', nameEn: 'Step-up', muscleGroup: 'LEGS', equipment: 'Bodyweight' },
  { namePt: 'Step up com halteres', nameEn: 'Dumbbell Step-up', muscleGroup: 'LEGS', equipment: 'Dumbbell' },
  { namePt: 'Panturrilha em pe', nameEn: 'Standing Calf Raise', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Panturrilha com halteres', nameEn: 'Dumbbell Calf Raise', muscleGroup: 'LEGS', equipment: 'Dumbbell' },
  { namePt: 'Panturrilha sentado', nameEn: 'Seated Calf Raise', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Panturrilha no leg press', nameEn: 'Leg Press Calf Raise', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Aducao de quadril', nameEn: 'Hip Adduction', muscleGroup: 'LEGS', equipment: 'Machine' },
  { namePt: 'Abducao de quadril', nameEn: 'Hip Abduction', muscleGroup: 'LEGS', equipment: 'Machine' },

  // SHOULDERS - 16 exercises
  { namePt: 'Desenvolvimento militar', nameEn: 'Overhead Press', muscleGroup: 'SHOULDERS', equipment: 'Barbell' },
  { namePt: 'Desenvolvimento com halteres', nameEn: 'Dumbbell Shoulder Press', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Desenvolvimento maquina', nameEn: 'Machine Shoulder Press', muscleGroup: 'SHOULDERS', equipment: 'Machine' },
  { namePt: 'Desenvolvimento sentado', nameEn: 'Seated Shoulder Press', muscleGroup: 'SHOULDERS', equipment: 'Barbell' },
  { namePt: 'Elevacao lateral', nameEn: 'Lateral Raise', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Elevacao lateral no cabo', nameEn: 'Cable Lateral Raise', muscleGroup: 'SHOULDERS', equipment: 'Cable' },
  { namePt: 'Elevacao frontal', nameEn: 'Front Raise', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Elevacao frontal no cabo', nameEn: 'Cable Front Raise', muscleGroup: 'SHOULDERS', equipment: 'Cable' },
  { namePt: 'Crucifixo invertido', nameEn: 'Reverse Fly', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Crucifixo invertido no cabo', nameEn: 'Cable Reverse Fly', muscleGroup: 'SHOULDERS', equipment: 'Cable' },
  { namePt: 'Face pull', nameEn: 'Face Pull', muscleGroup: 'SHOULDERS', equipment: 'Cable' },
  { namePt: 'Encolher ombros', nameEn: 'Shrug', muscleGroup: 'SHOULDERS', equipment: 'Barbell' },
  { namePt: 'Encolher ombros com halteres', nameEn: 'Dumbbell Shrug', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Elevacao traseira maquina', nameEn: 'Machine Rear Raise', muscleGroup: 'SHOULDERS', equipment: 'Machine' },
  { namePt: 'Desenvolvimento Arnold', nameEn: 'Arnold Press', muscleGroup: 'SHOULDERS', equipment: 'Dumbbell' },
  { namePt: 'Crucifixo deltoide posterior', nameEn: 'Rear Delt Fly', muscleGroup: 'SHOULDERS', equipment: 'Machine' },

  // BICEPS - 12 exercises
  { namePt: 'Rosca direta', nameEn: 'Barbell Curl', muscleGroup: 'BICEPS', equipment: 'Barbell' },
  { namePt: 'Rosca alternada', nameEn: 'Alternating Dumbbell Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Rosca com halteres', nameEn: 'Dumbbell Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Rosca martelo', nameEn: 'Hammer Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Rosca concentrada', nameEn: 'Concentration Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Rosca Scott', nameEn: 'Preacher Curl', muscleGroup: 'BICEPS', equipment: 'Machine' },
  { namePt: 'Rosca no cabo', nameEn: 'Cable Curl', muscleGroup: 'BICEPS', equipment: 'Cable' },
  { namePt: 'Rosca inversa', nameEn: 'Reverse Curl', muscleGroup: 'BICEPS', equipment: 'Barbell' },
  { namePt: 'Rosca inclinada', nameEn: 'Incline Dumbbell Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Rosca no banco Scott', nameEn: 'EZ-Bar Preacher Curl', muscleGroup: 'BICEPS', equipment: 'Machine' },
  { namePt: 'Rosca no banco inclinado', nameEn: 'Incline Bench Curl', muscleGroup: 'BICEPS', equipment: 'Dumbbell' },
  { namePt: 'Puxada do biceps', nameEn: 'Bicep Pushdown', muscleGroup: 'BICEPS', equipment: 'Cable' },

  // TRICEPS - 13 exercises
  { namePt: 'Triceps pulley', nameEn: 'Tricep Pushdown', muscleGroup: 'TRICEPS', equipment: 'Cable' },
  { namePt: 'Triceps pulley com corda', nameEn: 'Rope Tricep Pushdown', muscleGroup: 'TRICEPS', equipment: 'Cable' },
  { namePt: 'Triceps frances', nameEn: 'French Press', muscleGroup: 'TRICEPS', equipment: 'Dumbbell' },
  { namePt: 'Triceps testa', nameEn: 'Skull Crusher', muscleGroup: 'TRICEPS', equipment: 'Barbell' },
  { namePt: 'Triceps testa com halteres', nameEn: 'Dumbbell Skull Crusher', muscleGroup: 'TRICEPS', equipment: 'Dumbbell' },
  { namePt: 'Mergulho no banco', nameEn: 'Bench Dip', muscleGroup: 'TRICEPS', equipment: 'Bodyweight' },
  { namePt: 'Mergulho entre barras', nameEn: 'Parallel Dip', muscleGroup: 'TRICEPS', equipment: 'Bodyweight' },
  { namePt: 'Triceps coice', nameEn: 'Tricep Kickback', muscleGroup: 'TRICEPS', equipment: 'Dumbbell' },
  { namePt: 'Extensao de triceps no cabo', nameEn: 'Cable Overhead Tricep Extension', muscleGroup: 'TRICEPS', equipment: 'Cable' },
  { namePt: 'Extensao de triceps com halteres', nameEn: 'Dumbbell Overhead Tricep Extension', muscleGroup: 'TRICEPS', equipment: 'Dumbbell' },
  { namePt: 'Triceps na maquina', nameEn: 'Machine Tricep Press', muscleGroup: 'TRICEPS', equipment: 'Machine' },
  { namePt: 'Triceps com corrente', nameEn: 'Chain Tricep Dip', muscleGroup: 'TRICEPS', equipment: 'Bodyweight' },
  { namePt: 'Extensao testa no banco Smith', nameEn: 'Smith Machine Skull Crusher', muscleGroup: 'TRICEPS', equipment: 'Machine' },

  // ABS - 12 exercises
  { namePt: 'Abdominal crunch', nameEn: 'Crunch', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Abdominal crunch na maquina', nameEn: 'Machine Crunch', muscleGroup: 'ABS', equipment: 'Machine' },
  { namePt: 'Abdominal infra', nameEn: 'Leg Raise', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Abdominal infra pendurado', nameEn: 'Hanging Leg Raise', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Prancha', nameEn: 'Plank', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Prancha lateral', nameEn: 'Side Plank', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Abdominal bicicleta', nameEn: 'Bicycle Crunch', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Russian twist', nameEn: 'Russian Twist', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Abdominal no cabo', nameEn: 'Cable Crunch', muscleGroup: 'ABS', equipment: 'Cable' },
  { namePt: 'Abdominal pendurado', nameEn: 'Hanging Crunch', muscleGroup: 'ABS', equipment: 'Bodyweight' },
  { namePt: 'Abdominal com halteres', nameEn: 'Weighted Crunch', muscleGroup: 'ABS', equipment: 'Dumbbell' },
  { namePt: 'Abdominal obliquo', nameEn: 'Oblique Crunch', muscleGroup: 'ABS', equipment: 'Bodyweight' },

  // GLUTES - 12 exercises
  { namePt: 'Hip thrust', nameEn: 'Hip Thrust', muscleGroup: 'GLUTES', equipment: 'Barbell' },
  { namePt: 'Hip thrust com halteres', nameEn: 'Dumbbell Hip Thrust', muscleGroup: 'GLUTES', equipment: 'Dumbbell' },
  { namePt: 'Glute bridge', nameEn: 'Glute Bridge', muscleGroup: 'GLUTES', equipment: 'Bodyweight' },
  { namePt: 'Glute bridge single leg', nameEn: 'Single-leg Glute Bridge', muscleGroup: 'GLUTES', equipment: 'Bodyweight' },
  { namePt: 'Coice no cabo', nameEn: 'Cable Kickback', muscleGroup: 'GLUTES', equipment: 'Cable' },
  { namePt: 'Coice unilateral', nameEn: 'Donkey Kick', muscleGroup: 'GLUTES', equipment: 'Bodyweight' },
  { namePt: 'Abducao de quadril', nameEn: 'Hip Abduction', muscleGroup: 'GLUTES', equipment: 'Machine' },
  { namePt: 'Abducao de quadril no cabo', nameEn: 'Cable Hip Abduction', muscleGroup: 'GLUTES', equipment: 'Cable' },
  { namePt: 'Coice de 45', nameEn: '45-Degree Hip Extension', muscleGroup: 'GLUTES', equipment: 'Machine' },
  { namePt: 'Agachamento sumo', nameEn: 'Sumo Squat', muscleGroup: 'GLUTES', equipment: 'Bodyweight' },
  { namePt: 'Agachamento sumo com halteres', nameEn: 'Dumbbell Sumo Squat', muscleGroup: 'GLUTES', equipment: 'Dumbbell' },
  { namePt: 'Agachamento pliometrico', nameEn: 'Jump Squat', muscleGroup: 'GLUTES', equipment: 'Bodyweight' },

  // CARDIO - 10 exercises
  { namePt: 'Corrida na esteira', nameEn: 'Treadmill Run', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Caminhada na esteira', nameEn: 'Treadmill Walk', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Bicicleta ergometrica', nameEn: 'Stationary Bike', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Bicicleta ergometrica deitado', nameEn: 'Recumbent Bike', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Remo ergometrico', nameEn: 'Rowing Machine', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Escada', nameEn: 'Stair Climber', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Cross trainer', nameEn: 'Elliptical Machine', muscleGroup: 'CARDIO', equipment: 'Machine' },
  { namePt: 'Polichinelo', nameEn: 'Jumping Jack', muscleGroup: 'CARDIO', equipment: 'Bodyweight' },
  { namePt: 'Corda de pular', nameEn: 'Jump Rope', muscleGroup: 'CARDIO', equipment: 'Bodyweight' },
  { namePt: 'Corrida no lugar', nameEn: 'High Knees Run', muscleGroup: 'CARDIO', equipment: 'Bodyweight' },

  // FULL BODY - 10 exercises
  { namePt: 'Burpee', nameEn: 'Burpee', muscleGroup: 'FULL_BODY', equipment: 'Bodyweight' },
  { namePt: 'Burpee com flexao', nameEn: 'Burpee with Push-up', muscleGroup: 'FULL_BODY', equipment: 'Bodyweight' },
  { namePt: 'Kettlebell swing', nameEn: 'Kettlebell Swing', muscleGroup: 'FULL_BODY', equipment: 'Kettlebell' },
  { namePt: 'Thruster', nameEn: 'Thruster', muscleGroup: 'FULL_BODY', equipment: 'Dumbbell' },
  { namePt: 'Thruster com halteres', nameEn: 'Dumbbell Thruster', muscleGroup: 'FULL_BODY', equipment: 'Dumbbell' },
  { namePt: 'Clean and press', nameEn: 'Clean and Press', muscleGroup: 'FULL_BODY', equipment: 'Barbell' },
  { namePt: 'Farmer walk', nameEn: 'Farmer Walk', muscleGroup: 'FULL_BODY', equipment: 'Dumbbell' },
  { namePt: 'Mountain climbers', nameEn: 'Mountain Climber', muscleGroup: 'FULL_BODY', equipment: 'Bodyweight' },
  { namePt: 'Bear crawl', nameEn: 'Bear Crawl', muscleGroup: 'FULL_BODY', equipment: 'Bodyweight' },
  { namePt: 'Indian club swing', nameEn: 'Indian Club Swing', muscleGroup: 'FULL_BODY', equipment: 'Bodyweight' },

  // OTHER - 6 exercises
  { namePt: 'Mobilidade de quadril', nameEn: 'Hip Mobility Drill', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
  { namePt: 'Alongamento posterior', nameEn: 'Hamstring Stretch', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
  { namePt: 'Alongamento peitoral', nameEn: 'Chest Stretch', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
  { namePt: 'Aquecimento geral', nameEn: 'General Warm-up', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
  { namePt: 'Desaquecimento', nameEn: 'Cool-down', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
  { namePt: 'Flexibilidade geral', nameEn: 'General Flexibility', muscleGroup: 'OTHER', equipment: 'Bodyweight' },
]
